
title: Rxsi Blog
author: Rxsi
email: rxsing1331@gmail.com
description: ""
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

paginate: 15
paginate_path: "page/:num"
baseurl: ""

permalink: /posts/:title/


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css, tags.css]
      scripts : [tags.js, script.js]


texture:
  title: Rxsi Blog
  tagline: GameServer Developer
  date_format: "%b %-d, %Y" #"%Y-%m-%d"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    # twitter: chrisyu0229
    github:  rxsi
    # weibo: 6189403394
    email: rxsing1331@gmail.com
github:
  username: rxsi
gitalk:
    repo: rxsi.github.io
    client_id: 35b176842b84bc95da1c
    client_secret: 71d79ed5a525f1e5beabaeacc3973413e35d6a1b


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
#  - jekyll-feed
